kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ssd
