# GENERATED FILE. Use with Kubernetes 1.7+
# TO UPDATE, modify files in install/kubernetes/templates/helm/istio and run install/updateVersion.sh
global:
  proxy:
    repository: docker.io/istio/proxy
    tag: 0.5.0
  sidecar-injector:
    repository: docker.io/istio/sidecar_injector
    tag: 0.5.0
  mixer:
    repository: docker.io/istio/mixer
    tag: 0.5.0
  pilot:
    repository: docker.io/istio/pilot
    tag: 0.5.0
  security:
    repository: docker.io/istio/istio-ca
    tag: 0.5.0
  # Not recommended for user to configure this. Hyperkube image to use when creating custom resources
  hyperkube:
    repository: quay.io/coreos/hyperkube
    tag: v1.7.6_coreos.0

  # create RBAC resources
  rbacEnabled: true
  # mutual TLS authentication
  securityEnabled: false

#
# proxy side car and ingress configuration
#
serviceAccountName: default
imagePullPolicy: IfNotPresent
resources: {}
nodeSelector: {}
# istio ingress configuration
service:
  # By default istio ingress uses LoadBalancer type of service
  # to use NodePort, it needs to be enabled and desired port specified
  nodePort:
    enabled: false
    port: 32000

#
# initializer configuration
#
initializer:
  enabled: true
  serviceAccountName: default # used only if RBAC is not enabled
  replicaCount: 1
  imagePullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}

  initImage:
    repository: docker.io/istio/proxy_init
    tag: 0.4.0

#
# mixer configuration
#
mixer:
  enabled: true
  serviceAccountName: default # # used only if RBAC is not enabled
  replicaCount: 1
  imagePullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}

  prometheusStatsdExporter:
    repository: prom/statsd-exporter
    tag: latest
    imagePullPolicy: IfNotPresent
    resources: {}

#
# pilot configuration
#
pilot:
  enabled: true
  serviceAccountName: default # # used only if RBAC is not enabled
  replicaCount: 1
  imagePullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}

#
# security configuration
#
security:
  serviceAccountName: default # # used only if RBAC is not enabled
  replicaCount: 1
  imagePullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}
