apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "initializer.fullname" . }}
  labels:
    app: {{ template "initializer.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config: |-
    policy: "enabled"
    namespaces: [""] # everything, aka v1.NamespaceAll, aka cluster-wide
    initializerName: "sidecar.initializer.istio.io"
    params:
      initImage: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
      proxyImage: "{{ .Values.global.proxy.repository }}:{{ .Values.global.proxy.tag }}"
      verbosity: 2
      version: {{ .Values.global.proxy.tag }}
      meshConfigMapName: {{ template "istio.configmap.fullname" . }}
      imagePullPolicy: IfNotPresent
      debugMode: true
