# https://squidfunk.github.io/mkdocs-material/
# site_name: My Docs
# theme:
#   name: 'material'
#   palette:
#     primary: 'purple'
#     accent: 'indigo'
#     # primary: 'indigo'
#     # accent: 'indigo'
# #   logo: 'images/logo.svg'
#   logo:
#     icon: 'cloud'
#   favicon: 'assets/images/favicon.ico'
#   feature:
#     tabs: true
# repo_name: 'squidfunk/mkdocs-material'
# repo_url: 'https://github.com/squidfunk/mkdocs-material'
# extra:
#   repo_icon: gitlab
#   social:
#     - type: 'github'
#       link: 'https://github.com/squidfunk'
#     - type: 'twitter'
#       link: 'https://twitter.com/squidfunk'
#     - type: 'linkedin'
#       link: 'https://linkedin.com/in/squidfunk'
#   google_analytics:
#   - 'UA-XXXXXXXX-X'
#   - 'auto'
#   disqus: 'mkdocs-material'
# markdown_extensions:
#   - admonition
#   - codehilite:
#       guess_lang: false
#   - toc:
#       permalink: true
# Project information
site_name: 'Material for MkDocs'
site_description: 'A Material Design theme for MkDocs'
site_author: 'Martin Donath'
site_url: 'https://squidfunk.github.io/mkdocs-material/'

# Repository
repo_name: 'squidfunk/mkdocs-material'
repo_url: 'https://github.com/squidfunk/mkdocs-material'

# Copyright
copyright: 'Copyright &copy; 2016 - 2017 Martin Donath'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/squidfunk'
    - type: 'twitter'
      link: 'https://twitter.com/squidfunk'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/squidfunk'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
